[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ensembleset"
version = "1.0-alpha.22"
authors = [
  { name="George Perdrizet", email="george@perdrizet.org" },
]
description = "Ensemble dataset generator for tabular data prediction and modeling projects."
readme = "README.md"
license = {text = "GPLv3"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["optimization", "ensemble-learning", "ensemble-techniques", "feature-engineering", "machine-learning", "data-science"]

dependencies = [
  "h5py",
  "numpy",
  "pandas",
  "scikit-learn"
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "matplotlib"
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "nbsphinx",
    "pandoc"
]

[project.urls]
Homepage = "https://github.com/gperdrizet/ensembleset"
Repository = "https://github.com/gperdrizet/ensembleset"
Issues = "https://github.com/gperdrizet/ensembleset/issues"
PyPI = "https://pypi.org/project/ensembleset"

[tool.setuptools]
packages = ["ensembleset"]